engine:
  type: "in_memory"
network:
  addr: ":7991"
  max_connections: 100
  max_message_size: 4096
  idle_timeout: 2m
  write_timeout: 15s
logging:
  level: "debug"
  format: "text"
wal:
  enabled: true
  flushing_batch_size: 100
  flushing_batch_interval: "10ms"
  max_segment_size: 1024
  data_directory: "./data/wal"
replication:
  enabled: true
  replica_type: "master"
  master_addr: ":3232"
  sync_interval: 1s