// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: contract/replication.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_UNKNOWN   ErrorCode = 0
	ErrorCode_INTERNAL  ErrorCode = 1
	ErrorCode_NOT_FOUND ErrorCode = 2
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INTERNAL",
		2: "NOT_FOUND",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN":   0,
		"INTERNAL":  1,
		"NOT_FOUND": 2,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_replication_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_contract_replication_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_contract_replication_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=schema.v1.ErrorCode" json:"code,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_contract_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_contract_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_contract_replication_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_UNKNOWN
}

func (x *Error) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type NextSegmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LastSegmentName string                 `protobuf:"bytes,2,opt,name=last_segment_name,json=lastSegmentName,proto3" json:"last_segment_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NextSegmentRequest) Reset() {
	*x = NextSegmentRequest{}
	mi := &file_contract_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextSegmentRequest) ProtoMessage() {}

func (x *NextSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextSegmentRequest.ProtoReflect.Descriptor instead.
func (*NextSegmentRequest) Descriptor() ([]byte, []int) {
	return file_contract_replication_proto_rawDescGZIP(), []int{1}
}

func (x *NextSegmentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NextSegmentRequest) GetLastSegmentName() string {
	if x != nil {
		return x.LastSegmentName
	}
	return ""
}

type NextSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	SegmentName   string                 `protobuf:"bytes,2,opt,name=segment_name,json=segmentName,proto3" json:"segment_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextSegmentResponse) Reset() {
	*x = NextSegmentResponse{}
	mi := &file_contract_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextSegmentResponse) ProtoMessage() {}

func (x *NextSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextSegmentResponse.ProtoReflect.Descriptor instead.
func (*NextSegmentResponse) Descriptor() ([]byte, []int) {
	return file_contract_replication_proto_rawDescGZIP(), []int{2}
}

func (x *NextSegmentResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *NextSegmentResponse) GetSegmentName() string {
	if x != nil {
		return x.SegmentName
	}
	return ""
}

func (x *NextSegmentResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_contract_replication_proto protoreflect.FileDescriptor

const file_contract_replication_proto_rawDesc = "" +
	"\n" +
	"\x1acontract/replication.proto\x12\tschema.v1\"E\n" +
	"\x05Error\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.schema.v1.ErrorCodeR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"_\n" +
	"\x12NextSegmentRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12*\n" +
	"\x11last_segment_name\x18\x02 \x01(\tR\x0flastSegmentName\"t\n" +
	"\x13NextSegmentResponse\x12&\n" +
	"\x05error\x18\x01 \x01(\v2\x10.schema.v1.ErrorR\x05error\x12!\n" +
	"\fsegment_name\x18\x02 \x01(\tR\vsegmentName\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data*5\n" +
	"\tErrorCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bINTERNAL\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02BDZBgithub.com/Mort4lis/memdb/internal/db/storage/replication/contractb\x06proto3"

var (
	file_contract_replication_proto_rawDescOnce sync.Once
	file_contract_replication_proto_rawDescData []byte
)

func file_contract_replication_proto_rawDescGZIP() []byte {
	file_contract_replication_proto_rawDescOnce.Do(func() {
		file_contract_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_replication_proto_rawDesc), len(file_contract_replication_proto_rawDesc)))
	})
	return file_contract_replication_proto_rawDescData
}

var file_contract_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contract_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_contract_replication_proto_goTypes = []any{
	(ErrorCode)(0),              // 0: schema.v1.ErrorCode
	(*Error)(nil),               // 1: schema.v1.Error
	(*NextSegmentRequest)(nil),  // 2: schema.v1.NextSegmentRequest
	(*NextSegmentResponse)(nil), // 3: schema.v1.NextSegmentResponse
}
var file_contract_replication_proto_depIdxs = []int32{
	0, // 0: schema.v1.Error.code:type_name -> schema.v1.ErrorCode
	1, // 1: schema.v1.NextSegmentResponse.error:type_name -> schema.v1.Error
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contract_replication_proto_init() }
func file_contract_replication_proto_init() {
	if File_contract_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_replication_proto_rawDesc), len(file_contract_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_replication_proto_goTypes,
		DependencyIndexes: file_contract_replication_proto_depIdxs,
		EnumInfos:         file_contract_replication_proto_enumTypes,
		MessageInfos:      file_contract_replication_proto_msgTypes,
	}.Build()
	File_contract_replication_proto = out.File
	file_contract_replication_proto_goTypes = nil
	file_contract_replication_proto_depIdxs = nil
}
