// Code generated by mockery v2.51.1. DO NOT EDIT.

package wal

import (
	iter "iter"

	mock "github.com/stretchr/testify/mock"
)

// MockSegmentDirectory is an autogenerated mock type for the SegmentDirectory type
type MockSegmentDirectory struct {
	mock.Mock
}

// List provides a mock function with no fields
func (_m *MockSegmentDirectory) List() iter.Seq2[[]byte, error] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 iter.Seq2[[]byte, error]
	if rf, ok := ret.Get(0).(func() iter.Seq2[[]byte, error]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[[]byte, error])
		}
	}

	return r0
}

// NewMockSegmentDirectory creates a new instance of MockSegmentDirectory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSegmentDirectory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSegmentDirectory {
	mock := &MockSegmentDirectory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
