// Code generated by mockery v2.51.1. DO NOT EDIT.

package wal

import mock "github.com/stretchr/testify/mock"

// MockSegmentWriter is an autogenerated mock type for the SegmentWriter type
type MockSegmentWriter struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockSegmentWriter) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: _a0
func (_m *MockSegmentWriter) Write(_a0 []byte) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSegmentWriter creates a new instance of MockSegmentWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSegmentWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSegmentWriter {
	mock := &MockSegmentWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
